name: CI

on:
  # only runs on pushes to main branch
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-test:
    uses: alexwolek/foobar/.github/workflows/dotnet-reusable.yml@main
    needs: docker-build
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  docker-build:
    uses: alexwolek/foobar/.github/workflows/docker-reusable.yml@main
    needs: build-and-test
    with:
      image_name: ${{ github.repository }}.api
      username: ${{ github.repository_owner }}
      push: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  terraform:
    uses: alexwolek/foobar/.github/workflows/terraform-reusable.yml@main
    needs: docker-build
