name: CI

on:
  push:
    paths: 
    - 'src/**'
    - 'tests/**'
    - '**.sln'
    - '.github/workflows/dotnet-build.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: | 
        dotnet test \
        -c Release \
        --no-restore \
        /p:CollectCoverage=true \
        /p:CoverletOutput=TestResults/ \
        /p:CoverletOutputFormat=opencover

    - name: codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true

  docker-build:
    uses: alexwolek/foobar/.github/workflows/docker-reusable.yml@d940221a98295d165066188588a5c506dbe98bf2
    with:
      image_name: ${{ github.repository }}.api
      username: ${{ github.repository_owner }}
      push: github.ref == 'refs/heads/main'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
