name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'src/**'
      - '**.sln'
      - 'Dockerfile'
      - '.github/workflows/docker-image.yml'
      - '.github/workflows/docker-reusable.yml'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker-build:
    uses: alexwolek/foobar/.github/workflows/docker-reusable.yml@d940221a98295d165066188588a5c506dbe98bf2
    with:
      image_name: ${{ github.repository }}.api
      username: ${{ github.repository_owner }}
      push: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
