name: Docker Image CI

on:
  push:
    paths: 
    - 'src/**'
    - '**.sln'
    - '.github/workflows/docker-image.yml'
  workflow_dispatch:

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag foobar.api:$(date +%s)
