name: Build and Push Tagged Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker-build:
    uses: alexwolek/foobar/.github/workflows/docker-reusable.yml@d940221a98295d165066188588a5c506dbe98bf2
    with:
      image_name: ${{ github.repository }}.api
      username: ${{ github.repository_owner }}
      push: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
