name: Reusable docker image build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      username:
        required: true
        type: string
      push:
        description: 'Should the docker image be pushed to the repository'
        default: false
        required: false
        type: boolean
    secrets:
      token:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ inputs.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=,suffix=,format=long
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}