name: .NET build and test

on:
  push:
    paths: 
    - 'src/**'
    - 'tests/**'
    - '**.sln'
    - '.github/workflows/dotnet-build.yml'
  workflow_dispatch:

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: | 
        dotnet test 
        -c Release \
        --no-restore \
        /p:CollectCoverage=true \
        /p:CoverletOutput=./test-resutls \
        /p:CoverletOutputFormat=opencover

    - name: codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./test-resutls.opencover.xml # optional
        verbose: true # optional (default = false)